//! The MCP tool surface exposed to hosted Claude sessions.
//!
//! [`TermherdMcp`] is an rmcp [`ServerHandler`]: it answers `tools/list` and
//! `tools/call` for the live-bridge tools. Each tool is a thin adapter — it
//! translates the call into a [`Request`] on the async-transport bridge, awaits
//! the timeout-bounded [`Reply`], and shapes it back into an MCP result. No state
//! and no `core` access live here; the shell owns `core::App` and answers on the
//! bridge, so a tool can never touch it directly.

use std::time::Duration;

use rmcp::{
    ErrorData, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        CallToolResult, ContentBlock, Implementation, ProtocolVersion, ServerCapabilities,
        ServerInfo,
    },
    schemars::JsonSchema,
    tool, tool_handler, tool_router,
};
use serde::{Deserialize, Serialize};
use termherd_core::keymap::ChordError;
use termherd_core::snapshot::DEFAULT_TEXT_LINES;
use termherd_core::workspace::SplitDir;
use termherd_core::{
    Action as KeymapAction, KeyChord, Section, SessionStatus, SnapshotFilter, TerminalScope,
};

use crate::shell::bridge::{
    Action, BridgeHandle, CallError, Press, PressStep, Reply, Request, SessionInfo, SessionKind,
};
use crate::snapshot_dto::{SnapshotDto, status_str};

/// How long a tool waits for the shell to answer before failing the caller.
/// Bounds the whole round-trip (enqueue + reply) via [`BridgeHandle::call`], so
/// a wedged shell surfaces as a tool error, never a hang (Q7).
const CALL_TIMEOUT: Duration = Duration::from_secs(5);

/// Default bound for `wait_for_status` when the caller names none. Long enough
/// for a real command, short enough that a forgotten wait reports back.
const DEFAULT_WAIT_MS: u64 = 30_000;

/// Hard cap on a wait, whatever the caller asks for — the outer Q7 guarantee
/// that no bridge call can park a caller indefinitely.
const MAX_WAIT_MS: u64 = 300_000;

/// Bound on a `screenshot` round-trip. Longer than [`CALL_TIMEOUT`]: it covers
/// an async window frame *plus* a multi-megapixel resample and PNG encode,
/// legitimately slower than a state read — but still bounded (Q7).
const SCREENSHOT_TIMEOUT: Duration = Duration::from_secs(15);

/// Default bound on a screenshot's width. Sized for a model's context, not for
/// a display: an unscaled retina window is megabytes of base64.
const DEFAULT_MAX_WIDTH: u32 = 1200;

/// Range a caller's `max_width` is clamped into. The floor keeps an image
/// legible; the ceiling keeps one tool call from swamping the context it is
/// supposed to inform.
const MIN_MAX_WIDTH: u32 = 64;
const MAX_MAX_WIDTH: u32 = 4096;

/// Bound on the status read-back after a wait timed out. Deliberately short: it
/// is a courtesy on top of an answer the caller has already earned, so it must
/// barely extend the wait it follows.
const READ_BACK_TIMEOUT: Duration = Duration::from_millis(250);

/// The live-bridge MCP server handler. Holds only the bridge into the shell —
/// cloned fresh per session by the transport's service factory.
#[derive(Clone)]
pub struct TermherdMcp {
    bridge: BridgeHandle,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl TermherdMcp {
    /// Build a handler over `bridge`. The tool router is generated by the
    /// `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(bridge: BridgeHandle) -> Self {
        Self {
            bridge,
            tool_router: Self::tool_router(),
        }
    }

    /// The spike tool: list the live terminal sessions termherd is hosting, each
    /// with its stable handle, so an MCP client can address them.
    #[tool(
        name = "list_sessions",
        description = "List the live terminal sessions termherd is hosting. Each \
                       row carries a stable `handle` (address it in later calls), \
                       the tab title, working directory, kind (shell or claude), \
                       the resumed Claude id if any, and current activity status."
    )]
    async fn list_sessions(&self) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::ListSessions, CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Sessions(sessions) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        let sessions = sessions.iter().map(SessionDto::from).collect();
        structured(SessionListDto { sessions })
    }

    /// A filterable, read-only snapshot of the whole workspace — the structured
    /// "DOM" a client reads to perceive termherd before acting. Light by default
    /// (structure only, no terminal text); scope terminal text to named handles.
    #[tool(
        name = "snapshot",
        description = "A filterable snapshot of termherd's whole state: config, \
                       the session-browser sidebar, and the open tabs with their \
                       panes (each pane's stable handle, kind, cwd, status). Light \
                       by default — no terminal text. Args (all optional): \
                       `sections` (any of \"config\", \"sidebar\", \"tabs\"; omit \
                       for all), `terminals` (session handles to include screen \
                       text for; omit for none — read the structure first, then \
                       request a handle), `text_lines` (trailing lines per \
                       requested terminal, default 40)."
    )]
    async fn snapshot(
        &self,
        Parameters(args): Parameters<SnapshotArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::Snapshot(args.into_filter()), CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Snapshot(snapshot) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        structured(SnapshotDto::from(&snapshot))
    }

    /// Open a new terminal session and focus it. → `open_session`.
    #[tool(
        name = "open_session",
        description = "Open a new terminal session and focus it. Args: `project` \
                       (working directory; omit for the home dir), `kind` \
                       (\"shell\" or \"claude\", default \"shell\"). Returns the \
                       new session's `focused_handle`."
    )]
    async fn open_session(
        &self,
        Parameters(args): Parameters<OpenArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let action = Action::Open {
            project: args.project,
            kind: match args.kind.as_deref() {
                None | Some("shell") => SessionKind::Shell,
                Some("claude") => SessionKind::Claude,
                Some(other) => {
                    return Err(ErrorData::invalid_params(
                        format!("unknown kind {other:?}; expected \"shell\" or \"claude\""),
                        None,
                    ));
                }
            },
        };
        self.act(action).await
    }

    /// Split a pane, opening a fresh session beside it. → `split_pane`.
    #[tool(
        name = "split_pane",
        description = "Split a pane, opening a fresh shell beside it and focusing \
                       it. Args: `direction` (\"vertical\" = side by side, \
                       \"horizontal\" = stacked; default \"vertical\"), `pane` \
                       (session handle to split; omit for the focused pane). \
                       Returns the new pane's `focused_handle`."
    )]
    async fn split_pane(
        &self,
        Parameters(args): Parameters<SplitArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let dir = match args.direction.as_deref() {
            None | Some("vertical") | Some("v") => SplitDir::Vertical,
            Some("horizontal") | Some("h") => SplitDir::Horizontal,
            Some(other) => {
                return Err(ErrorData::invalid_params(
                    format!("unknown direction {other:?}; expected \"vertical\" or \"horizontal\""),
                    None,
                ));
            }
        };
        let pane = parse_optional_handle(args.pane)?;
        self.act(Action::Split { pane, dir }).await
    }

    /// Move focus to the pane hosting a session. → `focus_pane`.
    #[tool(
        name = "focus_pane",
        description = "Move focus to the pane hosting a session, and hand it the \
                       keyboard. Args: `session` (its stable handle). Returns the \
                       resulting `focused_handle`."
    )]
    async fn focus_pane(
        &self,
        Parameters(args): Parameters<FocusArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        self.act(Action::Focus { session }).await
    }

    /// Give a tab a manual name. → `rename_tab`.
    #[tool(
        name = "rename_tab",
        description = "Give the tab at `tab` (0-based index, as `snapshot` reports \
                       tab order) a manual name. A blank `title` reverts to the \
                       derived title. Returns the current `focused_handle`."
    )]
    async fn rename_tab(
        &self,
        Parameters(args): Parameters<RenameArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        self.act(Action::Rename {
            tab: args.tab,
            title: args.title,
        })
        .await
    }

    /// Add a repo to the sidebar, before it has any session. → `add_repo`.
    #[tool(
        name = "add_repo",
        description = "Add the repository at `path` to the sidebar, so it can be \
                       launched from before it has any Claude session. `path` is \
                       filed by the same rule the scan uses for a session's cwd: \
                       a git worktree collapses onto its main checkout, a file \
                       becomes its parent directory, anything else is kept as \
                       given — symlinks included, and NOT climbed to a repository \
                       root, so pass the directory you want the row for. The key \
                       actually kept comes back as `repo_path`; address the row \
                       with that, not with what you sent. A path that does not \
                       exist, or a relative one, is rejected."
    )]
    async fn add_repo(
        &self,
        Parameters(args): Parameters<RepoArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        self.act(Action::DeclareRepo { path: args.path }).await
    }

    /// Drop a repo's declaration. → `forget_repo`.
    #[tool(
        name = "forget_repo",
        description = "Remove a hand-added repository from the sidebar. The row \
                       survives if the scan still reports sessions for it — \
                       `in_sidebar` says which happened, and `session_count` why. \
                       Forgetting a repo that was never added is not an error."
    )]
    async fn forget_repo(
        &self,
        Parameters(args): Parameters<RepoArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        self.act(Action::ForgetRepo { path: args.path }).await
    }

    /// Close a pane; a lone pane closes its whole tab. → `close_pane`.
    #[tool(
        name = "close_pane",
        description = "Close a pane and kill its terminal. Args: `pane` (session \
                       handle to close; omit for the focused pane). A lone pane is \
                       its whole tab, which closes. Returns the resulting \
                       `focused_handle` (null when the workspace is now empty)."
    )]
    async fn close_pane(
        &self,
        Parameters(args): Parameters<CloseArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let pane = parse_optional_handle(args.pane)?;
        self.act(Action::Close { pane }).await
    }

    /// Type text into a session's terminal; the wait is a separate call.
    /// → `run_in_session`.
    #[tool(
        name = "run_in_session",
        description = "Type text into a session's terminal, as if typed at the \
                       keyboard. Returns as soon as the text is sent — it does \
                       not wait for the command to finish. To act on the result, \
                       follow with `wait_for_status` then `read_terminal`; do \
                       not poll `snapshot`, which races the transition you are \
                       watching for. Include a trailing newline in `text` to \
                       submit a command. Args: `session` (its stable handle), \
                       `text`. Returns the `focused_handle`."
    )]
    async fn run_in_session(
        &self,
        Parameters(args): Parameters<RunArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        self.act(Action::Run {
            session,
            bytes: args.text.into_bytes(),
        })
        .await
    }

    /// Block until a session's activity reaches one of the given statuses — the
    /// synchronisation half of `act → wait → observe`.
    #[tool(
        name = "wait_for_status",
        description = "Wait until a session's activity reaches one of `statuses` \
                       (default: idle or attention), then report it. Pair it \
                       with `run_in_session`, which returns immediately: run, \
                       wait, then `read_terminal`. Args: `session` (handle), \
                       `statuses` (any of \"starting\", \"busy\", \"idle\", \
                       \"attention\", \"exited\"), `timeout_ms` (default 30000, \
                       capped at 300000). A session that exits settles the wait \
                       whatever you asked for — it can no longer reach it. \
                       Returns `{ status, timed_out }`: on timeout the status is \
                       the session's current one, not an error."
    )]
    async fn wait_for_status(
        &self,
        Parameters(args): Parameters<WaitArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        let targets = parse_statuses(args.statuses)?;
        let timeout = wait_timeout(args.timeout_ms);

        match self
            .bridge
            .call(Request::WaitForStatus { session, targets }, timeout)
            .await
        {
            Ok(Reply::Waited(outcome)) => {
                if let Some(reason) = outcome.error {
                    return Err(ErrorData::invalid_params(reason, None));
                }
                structured(serde_json::json!({
                    "status": outcome.status.map(status_str),
                    "timed_out": false,
                }))
            }
            Ok(_) => Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            )),
            // The wait outlived its bound. Report *where the session got to*
            // rather than a bare failure: an agent that waited 30s needs the
            // current status to decide whether to keep waiting or give up.
            Err(CallError::Timeout(_)) => {
                let status = self.current_status(session).await;
                structured(serde_json::json!({
                    "status": status,
                    "timed_out": true,
                }))
            }
            Err(error) => Err(ErrorData::internal_error(error.to_string(), None)),
        }
    }

    /// The visible text of one session's terminal — the deep read `snapshot`
    /// deliberately leaves out.
    #[tool(
        name = "read_terminal",
        description = "Read the visible text of one session's terminal. Args: \
                       `session` (handle), `lines` (trailing lines to keep, \
                       default 40). Returns `{ text, rendered }`; `rendered` is \
                       false when the session is live but its screen has not \
                       been drawn yet — retry rather than giving up on the \
                       handle."
    )]
    async fn read_terminal(
        &self,
        Parameters(args): Parameters<ReadArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        let lines = args.lines.unwrap_or(DEFAULT_TEXT_LINES);
        let reply = self
            .bridge
            .call(Request::ReadTerminal { session, lines }, CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Terminal(read) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        if let Some(reason) = read.error {
            return Err(ErrorData::invalid_params(reason, None));
        }
        structured(serde_json::json!({
            "text": read.text.as_deref().unwrap_or_default(),
            "rendered": read.text.is_some(),
        }))
    }

    /// The window's pixels — what the text `snapshot` cannot show.
    #[tool(
        name = "screenshot",
        description = "Capture termherd's window as a PNG image — the pixel \
                       companion to the text `snapshot`, for render, colour and \
                       glyph questions text cannot answer. Args: `max_width` \
                       (bound on the returned width, default 1200, 64–4096); \
                       the frame is area-averaged down to fit, never upscaled, \
                       and a total-pixel ceiling bounds tall windows the width \
                       alone would not. The reported `width`/`height` are what \
                       you actually received. A default-bound window costs on \
                       the order of 200 kB of PNG, a third more again as \
                       base64 — lower `max_width` when a coarse view will do. \
                       Prefer \
                       `snapshot` / `read_terminal` for anything textual — they \
                       cost a fraction of the context an image does."
    )]
    async fn screenshot(
        &self,
        Parameters(args): Parameters<ScreenshotArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let max_width = args
            .max_width
            .unwrap_or(DEFAULT_MAX_WIDTH)
            .clamp(MIN_MAX_WIDTH, MAX_MAX_WIDTH);
        let reply = self
            .bridge
            .call(Request::Screenshot { max_width }, SCREENSHOT_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Shot(shot) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        let Some(png) = shot.png else {
            return Ok(no_pixels(shot.error));
        };
        let data = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &png);
        let mut result = CallToolResult::success(vec![ContentBlock::image(data, "image/png")]);
        // The size the caller *received*, which is not the size it asked for
        // when the window was smaller than the bound.
        result.structured_content = Some(structured_content(serde_json::json!({
            "width": shot.width,
            "height": shot.height,
        }))?);
        Ok(result)
    }

    /// Press key chords at termherd's own interface — the binding half of the
    /// keyboard surface.
    #[tool(
        name = "press_keys",
        description = "Press key chords at termherd's own interface (not at a \
                       terminal — typing into a session is `run_in_session`). \
                       Chords use the same syntax as the `keys` section of \
                       settings.json — \"cmd+shift+s\", \"ctrl+tab\", \
                       \"escape\" — and resolve through the *live* keymap, so \
                       this exercises whatever the user rebound. Args: `keys` \
                       (chords, applied in order). Returns one `steps` entry per \
                       chord — `ran` (with the action's name), `inert` (the \
                       action exists but has no surface yet, so nothing \
                       happened; do not retry), `overlay` (an open prompt \
                       consumed it; \"escape\" usually cancels and \"enter\" \
                       confirms — but on `quit-confirm` \"enter\" quits the app, \
                       killing every session and this connection, and \
                       `session-rename` answers to neither, so only a human can \
                       clear that one), \
                       `typed` (bound to nothing, so it reached the focused \
                       terminal), `unbound` (nothing claimed it) — plus the \
                       resulting `focused_handle`. Use `run_action` instead \
                       when you want the behaviour regardless of bindings."
    )]
    async fn press_keys(
        &self,
        Parameters(args): Parameters<PressKeysArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let presses = args
            .keys
            .iter()
            .map(|spec| {
                KeyChord::parse(spec)
                    .map(Press::Chord)
                    .map_err(|error| invalid_chord(spec, &error))
            })
            .collect::<Result<Vec<_>, _>>()?;
        self.press(presses, &args.keys).await
    }

    /// Run keymap actions by name — the behaviour half, stable across rebinds.
    #[tool(
        name = "run_action",
        description = "Run termherd's keymap actions by name, skipping the \
                       keymap — so it keeps working whatever the user rebound, \
                       where `press_keys` tests the binding itself. Names are \
                       the kebab-case ones the `keys` section of settings.json \
                       speaks: \"split-vertical\", \"next-tab\", \
                       \"toggle-sidebar\", \"capture\", \"activate-tab-3\". An \
                       unknown name is rejected and the error shows the syntax; \
                       this server serves tools only, so there is no resource to \
                       enumerate them from. Args: `actions` (applied in order). An open prompt still \
                       consumes an action, exactly as it consumes a keypress, \
                       and the step reports which one — answer it with \
                       `press_keys([\"enter\"])`. Returns `steps` plus the \
                       resulting `focused_handle`."
    )]
    async fn run_action(
        &self,
        Parameters(args): Parameters<RunActionArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let presses = args
            .actions
            .iter()
            .map(|name| {
                KeymapAction::from_config_name(name)
                    .map(Press::Command)
                    .ok_or_else(|| unknown_action(name))
            })
            .collect::<Result<Vec<_>, _>>()?;
        self.press(presses, &args.actions).await
    }
}

impl TermherdMcp {
    /// A session's current activity, read back after a wait timed out. Best
    /// effort by design: `None` covers a handle that no longer resolves *and* a
    /// read-back that failed. The likeliest cause of the original timeout is a
    /// wedged shell, which would fail this call too — and turning that into an
    /// error would swallow the `timed_out` answer the caller is owed.
    async fn current_status(&self, session: u64) -> Option<&'static str> {
        match self
            .bridge
            .call(Request::ListSessions, READ_BACK_TIMEOUT)
            .await
        {
            Ok(Reply::Sessions(sessions)) => sessions
                .iter()
                .find(|info| info.handle == session.to_string())
                .map(|info| status_str(info.status)),
            Ok(_) => None,
            Err(error) => {
                tracing::debug!(%error, "could not read the status back after a wait timeout");
                None
            }
        }
    }

    /// Send a press sequence over the bridge and shape its [`PressOutcome`] into
    /// a tool result. `requested` is what the caller asked for, echoed back into
    /// each step positionally: a caller reading "the third one hit an overlay"
    /// should not have to count its own arguments to learn which chord that was.
    async fn press(
        &self,
        presses: Vec<Press>,
        requested: &[String],
    ) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::Press(presses), CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Pressed(outcome) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        if let Some(reason) = outcome.error {
            return Err(ErrorData::internal_error(reason, None));
        }
        // The echo is positional, so a step count that does not match the press
        // count would silently truncate — or worse, misalign — into a report
        // indistinguishable from a correct one. The shell answers one step per
        // press, so this is a loud failure rather than a quiet wrong answer.
        if outcome.steps.len() != requested.len() {
            return Err(ErrorData::internal_error(
                format!(
                    "the shell answered {} steps for {} presses",
                    outcome.steps.len(),
                    requested.len()
                ),
                None,
            ));
        }
        let steps: Vec<PressStepDto> = outcome
            .steps
            .iter()
            .zip(requested)
            .map(|(step, press)| PressStepDto::new(press, step))
            .collect();
        structured(serde_json::json!({
            "steps": steps,
            "focused_handle": outcome.focused,
        }))
    }

    /// Send an [`Action`] over the bridge and shape its [`ActionOutcome`] into a
    /// tool result: a rejection (unknown handle / out-of-range tab) becomes an
    /// `invalid_params` error, an applied action a `{ focused_handle }` object.
    async fn act(&self, action: Action) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::Act(action), CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Acted(outcome) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        if let Some(reason) = outcome.error {
            return Err(ErrorData::invalid_params(reason, None));
        }
        let mut value = serde_json::json!({ "focused_handle": outcome.focused });
        // The repo actions answer about a sidebar row, not about focus; the
        // fields ride alongside rather than in a second reply kind.
        if let Some(repo) = outcome.repo
            && let Some(object) = value.as_object_mut()
        {
            object.insert("repo_path".into(), repo.path.into());
            object.insert("declared".into(), repo.declared.into());
            object.insert("session_count".into(), repo.session_count.into());
            object.insert("in_sidebar".into(), repo.visible.into());
        }
        structured(value)
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for TermherdMcp {
    fn get_info(&self) -> ServerInfo {
        // rmcp's `ServerInfo`/`Implementation` are `#[non_exhaustive]`, so build
        // from a default and set the fields we care about rather than a literal.
        let mut server = Implementation::from_build_env();
        server.name = "termherd".into();
        server.version = env!("CARGO_PKG_VERSION").into();

        let mut info = ServerInfo::default();
        info.protocol_version = ProtocolVersion::LATEST;
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = server;
        info.instructions = Some(
            "termherd's live bridge: read and (later) drive the terminal \
             sessions it is hosting."
                .into(),
        );
        info
    }
}

/// The `list_sessions` answer: the rows in an envelope, since
/// [`structured_content`] admits only an object.
#[derive(Serialize)]
struct SessionListDto {
    sessions: Vec<SessionDto>,
}

/// The on-the-wire shape of a session for the `list_sessions` tool: the stable
/// external handle plus flat, string-typed fields an MCP client can read without
/// knowing termherd's internal enums.
#[derive(Serialize)]
struct SessionDto {
    /// Stable external handle (the runtime session id).
    handle: String,
    title: String,
    cwd: Option<String>,
    /// `"shell"` or `"claude"`.
    kind: &'static str,
    /// The resumed Claude session id, if any (the *unstable* id — never the
    /// handle).
    resume_id: Option<String>,
    /// `"starting"`, `"busy"`, `"idle"`, `"attention"`, or `"exited"`.
    status: &'static str,
}

impl From<&SessionInfo> for SessionDto {
    fn from(info: &SessionInfo) -> Self {
        Self {
            handle: info.handle.clone(),
            title: info.title.clone(),
            cwd: info.cwd.clone(),
            kind: match info.kind {
                SessionKind::Shell => "shell",
                SessionKind::Claude => "claude",
            },
            resume_id: info.resume_id.clone(),
            status: status_str(info.status),
        }
    }
}

/// The `snapshot` tool's arguments — every field optional so a bare call is the
/// light default. Deserialised from the MCP `arguments` object.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct SnapshotArgs {
    /// Sections to include: any of `"config"`, `"sidebar"`, `"tabs"`. Omit for
    /// all three. Unknown names are ignored.
    #[serde(default)]
    sections: Option<Vec<String>>,
    /// Session handles (as strings, as `list_sessions` reports them) to include
    /// terminal text for. Omit (or empty) for none.
    #[serde(default)]
    terminals: Option<Vec<String>>,
    /// Include the focused pane's terminal text — a one-call shortcut when you
    /// don't yet know its handle. Ignored when `terminals` names handles.
    #[serde(default)]
    focused_terminal: Option<bool>,
    /// Trailing terminal lines to keep per requested session.
    #[serde(default)]
    text_lines: Option<usize>,
}

impl SnapshotArgs {
    /// Map the flat MCP arguments onto the core [`SnapshotFilter`]. Omitted
    /// fields fall back to the light default. Explicit handles win over the
    /// `focused_terminal` shortcut.
    fn into_filter(self) -> SnapshotFilter {
        let default = SnapshotFilter::default();
        let sections = match self.sections {
            Some(names) => names
                .iter()
                .filter_map(|name| match name.as_str() {
                    "config" => Some(Section::Config),
                    "sidebar" => Some(Section::Sidebar),
                    "tabs" => Some(Section::Tabs),
                    _ => None,
                })
                .collect(),
            None => default.sections,
        };
        let terminals = match self.terminals {
            Some(handles) if !handles.is_empty() => {
                TerminalScope::Only(handles.iter().filter_map(|h| h.parse().ok()).collect())
            }
            _ if self.focused_terminal == Some(true) => TerminalScope::Focused,
            _ => TerminalScope::None,
        };
        SnapshotFilter {
            sections,
            terminals,
            text_lines: self.text_lines.unwrap_or(default.text_lines),
        }
    }
}

/// Arguments for `open_session`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct OpenArgs {
    /// Working directory for the new session. Omit for the home directory.
    #[serde(default)]
    project: Option<String>,
    /// `"shell"` (default) or `"claude"`.
    #[serde(default)]
    kind: Option<String>,
}

/// Arguments for `split_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct SplitArgs {
    /// `"vertical"` (default, side by side) or `"horizontal"` (stacked).
    #[serde(default)]
    direction: Option<String>,
    /// Session handle to split. Omit for the focused pane.
    #[serde(default)]
    pane: Option<String>,
}

/// Arguments for `focus_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct FocusArgs {
    /// The stable handle of the session to focus.
    session: String,
}

/// Arguments for `rename_tab`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RenameArgs {
    /// 0-based tab index, as `snapshot` reports tab order.
    tab: usize,
    /// The new manual title; blank reverts to the derived title.
    title: String,
}

/// Arguments for `add_repo` and `forget_repo`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RepoArgs {
    /// An absolute directory. Filed by the scan's own key rule: a worktree
    /// collapses onto its main checkout, a file becomes its parent, anything
    /// else is kept as given — never climbed to a repository root.
    path: String,
}

/// Arguments for `close_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct CloseArgs {
    /// Session handle to close. Omit for the focused pane.
    #[serde(default)]
    pane: Option<String>,
}

/// Arguments for `run_in_session`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RunArgs {
    /// The stable handle of the target session.
    session: String,
    /// Text to type; include a trailing newline to submit a command.
    text: String,
}

/// A tool result carrying `payload` as its `structuredContent`.
fn structured<T: Serialize>(payload: T) -> Result<CallToolResult, ErrorData> {
    Ok(CallToolResult::structured(structured_content(payload)?))
}

/// `payload` as `structuredContent`, refused unless it is a JSON object.
///
/// MCP clients reject an array or a scalar on their schema check, before the
/// caller sees a byte — so every structured answer is shaped here, and a
/// payload that cannot be one is a programming error, not a caller's.
fn structured_content<T: Serialize>(payload: T) -> Result<serde_json::Value, ErrorData> {
    let value = serde_json::to_value(payload)
        .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
    if value.is_object() {
        Ok(value)
    } else {
        Err(ErrorData::internal_error(
            "structuredContent must be a JSON object; wrap this payload in one",
            None,
        ))
    }
}

/// A screenshot that produced no image, as a *tool-level* error: the caller
/// reads this text, where an `Err(ErrorData)` would be rendered opaquely by its
/// MCP client. It carries the shell's reason and the way forward — the text
/// `snapshot` needs no window and still answers.
fn no_pixels(reason: Option<String>) -> CallToolResult {
    let reason = reason.unwrap_or_else(|| "the window produced no image".to_owned());
    CallToolResult::error(vec![ContentBlock::text(format!(
        "{reason}. Use `snapshot` or `read_terminal` instead — they read the \
         workspace without the window."
    ))])
}

/// Parse a stable handle string (as `list_sessions` / `snapshot` report it) to
/// its numeric id, surfacing a non-numeric handle as an `invalid_params` error.
fn parse_handle(handle: &str) -> Result<u64, ErrorData> {
    handle
        .parse()
        .map_err(|_| ErrorData::invalid_params(format!("handle {handle:?} is not a number"), None))
}

/// Parse an optional handle: absent stays absent, present is validated.
fn parse_optional_handle(handle: Option<String>) -> Result<Option<u64>, ErrorData> {
    handle.map(|h| parse_handle(&h)).transpose()
}

/// Arguments for `wait_for_status`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct WaitArgs {
    /// The session handle to watch.
    session: String,
    /// Statuses that settle the wait. Omit for idle-or-attention.
    #[serde(default)]
    statuses: Option<Vec<String>>,
    /// How long to wait before reporting the current status instead.
    #[serde(default)]
    timeout_ms: Option<u64>,
}

/// Arguments for `screenshot`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct ScreenshotArgs {
    /// Bound on the returned image width, in pixels.
    #[serde(default)]
    max_width: Option<u32>,
}

/// Arguments for `press_keys`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct PressKeysArgs {
    /// Chord strings in `settings.json` syntax, applied in order.
    keys: Vec<String>,
}

/// Arguments for `run_action`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RunActionArgs {
    /// Kebab-case action names, applied in order.
    actions: Vec<String>,
}

/// The on-the-wire shape of one press: what was asked, what the routing ladder
/// did with it, and the detail that outcome carries.
#[derive(Debug, Serialize, PartialEq, Eq)]
struct PressStepDto {
    /// The chord or action name the caller asked for.
    press: String,
    /// `"ran"`, `"inert"`, `"overlay"`, `"typed"` or `"unbound"`.
    result: &'static str,
    /// The keymap action named, for `"ran"` and `"inert"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    action: Option<String>,
    /// Which overlay consumed it, for `"overlay"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    overlay: Option<String>,
    /// Why nothing happened, for `"inert"`: `"no-surface"` (the action is wired
    /// to nothing, so retrying is pointless) or `"no-context"` (a precondition
    /// was absent, which the caller can go and create).
    #[serde(skip_serializing_if = "Option::is_none")]
    reason: Option<&'static str>,
}

impl PressStepDto {
    /// Flatten one [`PressStep`] against the press that produced it. The detail
    /// fields are per-outcome, so each is omitted where it means nothing rather
    /// than sent as a null the caller has to interpret.
    fn new(press: &str, step: &PressStep) -> Self {
        let (result, action, overlay, reason) = match step {
            PressStep::Ran(name) => ("ran", Some(name.clone()), None, None),
            PressStep::Inert { action, reason } => {
                ("inert", Some(action.clone()), None, Some(*reason))
            }
            PressStep::Overlay(name) => ("overlay", None, Some(name.clone()), None),
            PressStep::Typed => ("typed", None, None, None),
            PressStep::Unbound => ("unbound", None, None, None),
        };
        Self {
            press: press.to_owned(),
            result,
            action,
            overlay,
            reason,
        }
    }
}

/// A chord string the keymap parser rejected. Names the offender and the syntax,
/// and rejects the **whole** call before anything applies — a half-applied
/// sequence is worse than none, since the caller cannot tell how far it got.
fn invalid_chord(spec: &str, error: &ChordError) -> ErrorData {
    ErrorData::invalid_params(
        format!(
            "chord {spec:?} does not parse: {error}. Use the settings.json \
             syntax — modifiers `ctrl`/`alt`/`shift`/`cmd` joined to one key by \
             `+`, e.g. \"cmd+shift+s\" (the literal plus key is spelled `plus`)."
        ),
        None,
    )
}

/// An action name that is in no keymap. Rejected rather than skipped, and
/// likewise before anything applies.
fn unknown_action(name: &str) -> ErrorData {
    ErrorData::invalid_params(
        format!(
            "unknown action {name:?}. Names are the kebab-case ones \
             settings.json speaks, e.g. \"split-vertical\", \"next-tab\", \
             \"activate-tab-3\"."
        ),
        None,
    )
}

/// Arguments for `read_terminal`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct ReadArgs {
    /// The session handle to read.
    session: String,
    /// Trailing lines to keep.
    #[serde(default)]
    lines: Option<usize>,
}

/// Map the named statuses onto the core enum. An empty or omitted list means
/// idle-or-attention — the two a caller waiting on a command actually wants.
/// An unknown name is rejected rather than dropped: silently waiting on fewer
/// statuses than asked is exactly the silent-catch trap to avoid.
fn parse_statuses(names: Option<Vec<String>>) -> Result<Vec<SessionStatus>, ErrorData> {
    let Some(names) = names.filter(|names| !names.is_empty()) else {
        return Ok(vec![SessionStatus::Idle, SessionStatus::Attention]);
    };
    names
        .iter()
        .map(|name| {
            status_from_str(name)
                .ok_or_else(|| ErrorData::invalid_params(format!("unknown status {name:?}"), None))
        })
        .collect()
}

/// The caller's bound for a wait, defaulted and capped. The cap is the outer
/// guarantee behind Q7: no bridge call, however it was parameterised, can park
/// a caller indefinitely.
fn wait_timeout(timeout_ms: Option<u64>) -> Duration {
    Duration::from_millis(timeout_ms.unwrap_or(DEFAULT_WAIT_MS).min(MAX_WAIT_MS))
}

/// The inverse of [`crate::snapshot_dto::status_str`] — the external word back
/// to the core enum.
fn status_from_str(name: &str) -> Option<SessionStatus> {
    match name {
        "starting" => Some(SessionStatus::Starting),
        "busy" => Some(SessionStatus::Busy),
        "idle" => Some(SessionStatus::Idle),
        "attention" => Some(SessionStatus::Attention),
        "exited" => Some(SessionStatus::Exited),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shell::bridge::{Reply, Request, ShotResult, channel, spawn_test_shell};
    use termherd_core::{App, Event, Launch, LaunchSpec, SessionStatus, SnapshotInputs};

    #[tokio::test]
    async fn list_sessions_tool_shapes_the_bridge_reply_into_structured_json() {
        let (handle, requests) = channel();
        // Stand in for the shell: answer the ListSessions call with one session.
        let shell = spawn_test_shell(
            requests,
            Reply::Sessions(vec![SessionInfo {
                handle: "7".into(),
                title: "proj".into(),
                cwd: Some("/proj".into()),
                kind: SessionKind::Claude,
                resume_id: Some("claude-xyz".into()),
                status: SessionStatus::Busy,
            }]),
        );

        let result = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect("the tool returns a result");

        assert_eq!(
            shell.await.expect("shell task"),
            Request::ListSessions,
            "the tool asked the bridge for the session list"
        );
        let value = result.structured_content.expect("structured json content");
        let rows = value["sessions"]
            .as_array()
            .cloned()
            .expect("the rows ride in a `sessions` field of the envelope");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0]["handle"], "7", "the stable handle is carried out");
        assert_eq!(rows[0]["kind"], "claude");
        assert_eq!(rows[0]["status"], "busy");
        assert_eq!(
            rows[0]["resume_id"], "claude-xyz",
            "the Claude id rides alongside the handle, not as it"
        );
    }

    #[tokio::test]
    async fn list_sessions_answers_an_object_even_with_no_sessions() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(requests, Reply::Sessions(Vec::new()));

        let result = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect("the tool returns a result");

        assert_eq!(
            result.structured_content.expect("structured json content"),
            serde_json::json!({ "sessions": [] }),
        );
    }

    #[test]
    fn structured_refuses_a_payload_that_is_not_an_object() {
        let error = structured(serde_json::json!([1, 2, 3]))
            .expect_err("a bare array is not valid structuredContent");
        assert!(
            error.message.contains("object"),
            "the error names the rule it enforces, got: {}",
            error.message
        );
    }

    /// A tool call in flight, boxed so one `match` can return any of them.
    type SweepCall<'a> =
        std::pin::Pin<Box<dyn Future<Output = Result<CallToolResult, ErrorData>> + 'a>>;

    /// The reply the shell must give for `tool`, and the call that drives it.
    ///
    /// One `match` states the tool list once, so a tool the sweep does not know
    /// panics here rather than being skipped in silence.
    fn sweep_case<'a>(mcp: &'a TermherdMcp, tool: &str) -> (Reply, SweepCall<'a>) {
        use crate::shell::bridge::{ActionOutcome, ShotResult, TerminalRead, WaitOutcome};

        let acted = || {
            Reply::Acted(ActionOutcome {
                focused: Some("1".into()),
                error: None,
                repo: None,
            })
        };
        match tool {
            "list_sessions" => (
                Reply::Sessions(Vec::new()),
                Box::pin(mcp.list_sessions()) as SweepCall<'a>,
            ),
            "snapshot" => (
                Reply::Snapshot(
                    App::new().snapshot(&SnapshotFilter::default(), &SnapshotInputs::default()),
                ),
                Box::pin(mcp.snapshot(Parameters(SnapshotArgs::default()))),
            ),
            "open_session" => (
                acted(),
                Box::pin(mcp.open_session(Parameters(OpenArgs::default()))),
            ),
            "split_pane" => (
                acted(),
                Box::pin(mcp.split_pane(Parameters(SplitArgs::default()))),
            ),
            "focus_pane" => (
                acted(),
                Box::pin(mcp.focus_pane(Parameters(FocusArgs {
                    session: "1".into(),
                }))),
            ),
            "rename_tab" => (
                acted(),
                Box::pin(mcp.rename_tab(Parameters(RenameArgs {
                    tab: 0,
                    title: "t".into(),
                }))),
            ),
            "add_repo" => (
                acted(),
                Box::pin(mcp.add_repo(Parameters(RepoArgs { path: "/p".into() }))),
            ),
            "forget_repo" => (
                acted(),
                Box::pin(mcp.forget_repo(Parameters(RepoArgs { path: "/p".into() }))),
            ),
            "close_pane" => (
                acted(),
                Box::pin(mcp.close_pane(Parameters(CloseArgs::default()))),
            ),
            "run_in_session" => (
                acted(),
                Box::pin(mcp.run_in_session(Parameters(RunArgs {
                    session: "1".into(),
                    text: "ls\n".into(),
                }))),
            ),
            "wait_for_status" => (
                Reply::Waited(WaitOutcome {
                    status: Some(SessionStatus::Idle),
                    error: None,
                }),
                Box::pin(mcp.wait_for_status(Parameters(WaitArgs {
                    session: "1".into(),
                    ..WaitArgs::default()
                }))),
            ),
            "read_terminal" => (
                Reply::Terminal(TerminalRead {
                    text: Some("hello".into()),
                    error: None,
                }),
                Box::pin(mcp.read_terminal(Parameters(ReadArgs {
                    session: "1".into(),
                    lines: None,
                }))),
            ),
            "press_keys" => (
                Reply::Pressed(PressOutcome {
                    steps: vec![PressStep::Unbound],
                    focused: Some("1".into()),
                    error: None,
                }),
                Box::pin(mcp.press_keys(Parameters(PressKeysArgs {
                    keys: vec!["escape".into()],
                }))),
            ),
            "run_action" => (
                Reply::Pressed(PressOutcome {
                    steps: vec![PressStep::Ran("close-focused".into())],
                    focused: Some("1".into()),
                    error: None,
                }),
                Box::pin(mcp.run_action(Parameters(RunActionArgs {
                    actions: vec!["close-focused".into()],
                }))),
            ),
            "screenshot" => (
                Reply::Shot(ShotResult {
                    png: Some(vec![0]),
                    width: 8,
                    height: 4,
                    error: None,
                }),
                Box::pin(mcp.screenshot(Parameters(ScreenshotArgs::default()))),
            ),
            other => panic!("tool {other:?} is new: add it to the structuredContent sweep"),
        }
    }

    #[tokio::test]
    async fn every_tool_answers_its_structured_content_as_an_object() {
        // The list comes from the router rather than from an enumeration typed
        // here, so a tool added later fails this sweep instead of slipping past.
        let tools: Vec<String> = TermherdMcp::tool_router()
            .list_all()
            .iter()
            .map(|tool| tool.name.to_string())
            .collect();
        assert!(!tools.is_empty(), "an empty router would pass vacuously");

        for tool in tools {
            let (handle, requests) = channel();
            let mcp = TermherdMcp::new(handle);
            let (reply, call) = sweep_case(&mcp, &tool);
            let _shell = spawn_test_shell(requests, reply);
            let result = call.await.unwrap_or_else(|error| {
                panic!("{tool} answered an error: {}", error.message);
            });
            let value = result
                .structured_content
                .unwrap_or_else(|| panic!("{tool} answers with structured content"));
            assert!(
                value.is_object(),
                "{tool} must answer a JSON object, got: {value}"
            );
        }
    }

    #[tokio::test]
    async fn list_sessions_tool_surfaces_a_bridge_failure_as_an_error() {
        // No shell answering: the bridge closes, and the tool must report an
        // error rather than hang (the silent-catch trap the substrate avoids).
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(
            error.message.contains("closed"),
            "the error names the closed bridge, got: {}",
            error.message
        );
    }

    #[test]
    fn snapshot_args_default_to_the_light_filter() {
        assert_eq!(
            SnapshotArgs::default().into_filter(),
            SnapshotFilter::default()
        );
    }

    #[test]
    fn snapshot_args_map_sections_terminals_and_text_lines() {
        let filter = SnapshotArgs {
            sections: Some(vec!["tabs".into(), "bogus".into()]),
            terminals: Some(vec!["3".into(), "4".into()]),
            text_lines: Some(10),
            ..SnapshotArgs::default()
        }
        .into_filter();
        // Unknown section names are dropped, not errors.
        assert_eq!(filter.sections, vec![Section::Tabs]);
        // String handles parse back to the numeric core scope.
        assert_eq!(filter.terminals, TerminalScope::Only(vec![3, 4]));
        assert_eq!(filter.text_lines, 10);
    }

    #[test]
    fn snapshot_args_with_empty_terminals_stay_text_free() {
        let filter = SnapshotArgs {
            terminals: Some(Vec::new()),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::None);
    }

    #[test]
    fn snapshot_args_focused_terminal_shortcut_scopes_to_the_focused_pane() {
        let filter = SnapshotArgs {
            focused_terminal: Some(true),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::Focused);

        // Explicit handles win over the shortcut.
        let filter = SnapshotArgs {
            terminals: Some(vec!["5".into()]),
            focused_terminal: Some(true),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::Only(vec![5]));
    }

    #[tokio::test]
    async fn snapshot_tool_shapes_the_bridge_reply_into_structured_json() {
        // Answer with a real snapshot of a one-Claude-tab workspace.
        let mut app = App::new();
        app.apply(Event::LaunchSession(LaunchSpec {
            cwd: Some("/proj".into()),
            launch: Launch::Claude { resume: None },
            title: "work".into(),
        }));
        let filter = SnapshotFilter::default();
        let snapshot = app.snapshot(&filter, &SnapshotInputs::default());

        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, Reply::Snapshot(snapshot));
        let result = TermherdMcp::new(handle)
            .snapshot(Parameters(SnapshotArgs::default()))
            .await
            .expect("the tool returns a result");

        assert!(
            matches!(shell.await.expect("shell task"), Request::Snapshot(_)),
            "the tool asked the bridge for a snapshot"
        );
        let value = result.structured_content.expect("structured json content");
        // Handles are strings on the wire, matching `list_sessions`.
        assert_eq!(
            value["focus"]["session"], "1",
            "the launched session is focused"
        );
        assert_eq!(value["tabs"][0]["title"], "work");
        assert_eq!(value["tabs"][0]["panes"][0]["handle"], "1");
        assert_eq!(value["tabs"][0]["panes"][0]["kind"], "claude");
        assert_eq!(value["tabs"][0]["panes"][0]["cwd"], "/proj");
        // Light default: no terminal text was requested, so none is present.
        assert!(
            value.get("terminals").is_none(),
            "no terminal text by default"
        );
    }

    #[tokio::test]
    async fn snapshot_tool_surfaces_a_bridge_failure_as_an_error() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .snapshot(Parameters(SnapshotArgs::default()))
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(error.message.contains("closed"), "got: {}", error.message);
    }

    // ---- Orchestration tools (F-mcp-orchestration) ----------------------

    use crate::shell::bridge::{Action, ActionOutcome};

    /// Run `call` against a shell that records the request and answers it with an
    /// applied outcome; return the `Action` the tool built.
    async fn action_of<F, Fut>(call: F) -> Action
    where
        F: FnOnce(TermherdMcp) -> Fut,
        Fut: std::future::Future<Output = Result<CallToolResult, ErrorData>>,
    {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::applied(Some("2".into()))),
        );
        call(TermherdMcp::new(handle))
            .await
            .expect("the tool returns a result");
        match shell.await.expect("shell task") {
            Request::Act(action) => action,
            other => panic!("expected an action request, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn open_session_tool_builds_an_open_action() {
        let action = action_of(|mcp| async move {
            mcp.open_session(Parameters(OpenArgs {
                project: Some("/proj".into()),
                kind: Some("claude".into()),
            }))
            .await
        })
        .await;
        assert_eq!(
            action,
            Action::Open {
                project: Some("/proj".into()),
                kind: SessionKind::Claude,
            }
        );
    }

    #[tokio::test]
    async fn open_session_tool_defaults_kind_to_shell() {
        let action =
            action_of(|mcp| async move { mcp.open_session(Parameters(OpenArgs::default())).await })
                .await;
        assert_eq!(
            action,
            Action::Open {
                project: None,
                kind: SessionKind::Shell,
            }
        );
    }

    #[tokio::test]
    async fn open_session_tool_rejects_an_unknown_kind() {
        let (handle, requests) = channel();
        drop(requests); // never reached: the arg is rejected before the bridge.
        let error = TermherdMcp::new(handle)
            .open_session(Parameters(OpenArgs {
                project: None,
                kind: Some("wizard".into()),
            }))
            .await
            .expect_err("an unknown kind is an invalid_params error");
        assert!(error.message.contains("wizard"), "got: {}", error.message);
    }

    #[tokio::test]
    async fn split_pane_tool_maps_direction_and_target() {
        let action = action_of(|mcp| async move {
            mcp.split_pane(Parameters(SplitArgs {
                direction: Some("horizontal".into()),
                pane: Some("5".into()),
            }))
            .await
        })
        .await;
        assert_eq!(
            action,
            Action::Split {
                pane: Some(5),
                dir: SplitDir::Horizontal,
            }
        );
    }

    #[tokio::test]
    async fn split_pane_tool_defaults_to_a_vertical_split_of_the_focused_pane() {
        let action =
            action_of(|mcp| async move { mcp.split_pane(Parameters(SplitArgs::default())).await })
                .await;
        assert_eq!(
            action,
            Action::Split {
                pane: None,
                dir: SplitDir::Vertical,
            }
        );
    }

    #[tokio::test]
    async fn focus_and_run_tools_carry_the_parsed_handle() {
        let focus = action_of(|mcp| async move {
            mcp.focus_pane(Parameters(FocusArgs {
                session: "3".into(),
            }))
            .await
        })
        .await;
        assert_eq!(focus, Action::Focus { session: 3 });

        let run = action_of(|mcp| async move {
            mcp.run_in_session(Parameters(RunArgs {
                session: "3".into(),
                text: "ls\n".into(),
            }))
            .await
        })
        .await;
        assert_eq!(
            run,
            Action::Run {
                session: 3,
                bytes: b"ls\n".to_vec(),
            }
        );
    }

    #[tokio::test]
    async fn run_in_session_tool_rejects_a_non_numeric_handle() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .run_in_session(Parameters(RunArgs {
                session: "not-a-number".into(),
                text: "x".into(),
            }))
            .await
            .expect_err("a non-numeric handle is rejected before the bridge");
        assert!(
            error.message.contains("not-a-number"),
            "got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn rename_and_close_tools_build_their_actions() {
        let rename = action_of(|mcp| async move {
            mcp.rename_tab(Parameters(RenameArgs {
                tab: 1,
                title: "build".into(),
            }))
            .await
        })
        .await;
        assert_eq!(
            rename,
            Action::Rename {
                tab: 1,
                title: "build".into(),
            }
        );

        let close = action_of(|mcp| async move {
            mcp.close_pane(Parameters(CloseArgs {
                pane: Some("4".into()),
            }))
            .await
        })
        .await;
        assert_eq!(close, Action::Close { pane: Some(4) });
    }

    #[tokio::test]
    async fn a_tool_surfaces_a_rejected_action_as_invalid_params() {
        // The shell answers with a rejection (unknown handle); the tool must
        // relay it as an error, not a success with a null handle.
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::rejected("no live session with handle 9")),
        );
        let error = TermherdMcp::new(handle)
            .focus_pane(Parameters(FocusArgs {
                session: "9".into(),
            }))
            .await
            .expect_err("a rejected action is a tool error");
        assert!(
            error.message.contains("handle 9"),
            "the rejection reason is relayed, got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn a_tool_reports_the_resulting_focus_on_success() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::applied(Some("2".into()))),
        );
        let result = TermherdMcp::new(handle)
            .split_pane(Parameters(SplitArgs::default()))
            .await
            .expect("the tool returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(
            value["focused_handle"], "2",
            "the new pane's handle is returned"
        );
    }

    #[tokio::test]
    async fn a_tool_surfaces_a_bridge_failure_as_an_error() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .close_pane(Parameters(CloseArgs::default()))
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(error.message.contains("closed"), "got: {}", error.message);
    }

    // --- wait_for_status / read_terminal ---

    use crate::shell::bridge::{TerminalRead, WaitOutcome, spawn_test_shell_seq};

    /// Args for a wait on `session`, otherwise defaulted.
    fn wait_args(session: &str) -> WaitArgs {
        WaitArgs {
            session: session.to_owned(),
            ..WaitArgs::default()
        }
    }

    /// Run `wait_for_status` against a shell answering `reply`, returning the
    /// request the tool built.
    async fn wait_request(args: WaitArgs, reply: Reply) -> Request {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, reply);
        let _ = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await;
        shell.await.expect("shell task")
    }

    /// A settled wait, as the shell would answer it.
    fn settled(status: SessionStatus) -> Reply {
        Reply::Waited(WaitOutcome {
            status: Some(status),
            error: None,
        })
    }

    #[tokio::test]
    async fn wait_for_status_defaults_to_idle_or_attention() {
        // The two a caller waiting on a command actually cares about: finished,
        // or stopped to ask something.
        let request = wait_request(wait_args("7"), settled(SessionStatus::Idle)).await;
        assert_eq!(
            request,
            Request::WaitForStatus {
                session: 7,
                targets: vec![SessionStatus::Idle, SessionStatus::Attention],
            }
        );
    }

    #[tokio::test]
    async fn wait_for_status_maps_the_named_statuses() {
        let args = WaitArgs {
            session: "7".into(),
            statuses: Some(vec!["busy".into(), "exited".into()]),
            ..WaitArgs::default()
        };
        let request = wait_request(args, settled(SessionStatus::Busy)).await;
        assert_eq!(
            request,
            Request::WaitForStatus {
                session: 7,
                targets: vec![SessionStatus::Busy, SessionStatus::Exited],
            }
        );
    }

    #[tokio::test]
    async fn wait_for_status_rejects_an_unknown_status_name() {
        // Dropping the unknown name and waiting on the rest would be the silent
        // catch this codebase exists to avoid.
        let (handle, requests) = channel();
        let args = WaitArgs {
            session: "7".into(),
            statuses: Some(vec!["idle".into(), "finished".into()]),
            ..WaitArgs::default()
        };
        let error = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect_err("an unknown status is rejected");
        assert!(error.message.contains("finished"), "got: {}", error.message);
        drop(requests);
    }

    #[tokio::test]
    async fn wait_for_status_reports_the_settled_status() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(requests, settled(SessionStatus::Attention));
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(wait_args("7")))
            .await
            .expect("the tool returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["status"], "attention");
        assert_eq!(value["timed_out"], false);
    }

    #[tokio::test]
    async fn wait_for_status_relays_an_unknown_handle_as_invalid_params() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Waited(WaitOutcome {
                status: None,
                error: Some("no live session with handle 7".into()),
            }),
        );
        let error = TermherdMcp::new(handle)
            .wait_for_status(Parameters(wait_args("7")))
            .await
            .expect_err("a rejected wait is a tool error");
        assert!(
            error.message.contains("no live session"),
            "got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn wait_for_status_reports_the_current_status_when_it_times_out() {
        // Timing out is not a failure: the agent needs to know *where* the
        // session got to, to decide between waiting again and giving up.
        let (handle, requests) = channel();
        let shell = spawn_test_shell_seq(
            requests,
            vec![
                // The wait itself: received, never answered.
                None,
                // The follow-up read of the current status.
                Some(Reply::Sessions(vec![SessionInfo {
                    handle: "7".into(),
                    title: "proj".into(),
                    cwd: None,
                    kind: SessionKind::Shell,
                    resume_id: None,
                    status: SessionStatus::Busy,
                }])),
            ],
        );
        let args = WaitArgs {
            session: "7".into(),
            timeout_ms: Some(50),
            ..WaitArgs::default()
        };
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect("a timed-out wait still returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["timed_out"], true);
        assert_eq!(
            value["status"], "busy",
            "the session's current status rides back with the timeout"
        );
        let seen = shell.await.expect("shell task");
        assert_eq!(seen.len(), 2, "the wait, then the status read-back");
        assert_eq!(seen[1], Request::ListSessions);
    }

    #[tokio::test]
    async fn a_wait_that_times_out_still_answers_when_the_read_back_fails() {
        // The likeliest cause of the original timeout is a wedged shell, which
        // fails the status read-back too. That must not swallow the `timed_out`
        // answer the caller already earned — it is the whole point of the path.
        let (handle, requests) = channel();
        // Neither the wait nor the read-back is ever answered.
        let shell = spawn_test_shell_seq(requests, vec![None, None]);
        let args = WaitArgs {
            session: "7".into(),
            timeout_ms: Some(50),
            ..WaitArgs::default()
        };
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect("a wedged shell still yields the timeout answer");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["timed_out"], true);
        assert!(
            value["status"].is_null(),
            "an unreadable status is null, not an error"
        );
        drop(shell);
    }

    #[test]
    fn a_wait_is_capped_however_long_the_caller_asks() {
        // The outer Q7 guarantee: no parameterisation parks a caller forever.
        assert_eq!(wait_timeout(None), Duration::from_millis(DEFAULT_WAIT_MS));
        assert_eq!(wait_timeout(Some(1_000)), Duration::from_millis(1_000));
        assert_eq!(
            wait_timeout(Some(u64::MAX)),
            Duration::from_millis(MAX_WAIT_MS)
        );
    }

    #[tokio::test]
    async fn read_terminal_passes_the_handle_and_line_budget() {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: Some("$ cargo test".into()),
                error: None,
            }),
        );
        let result = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: Some(5),
            }))
            .await
            .expect("the tool returns a result");
        assert_eq!(
            shell.await.expect("shell task"),
            Request::ReadTerminal {
                session: 7,
                lines: 5
            }
        );
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["text"], "$ cargo test");
        assert_eq!(value["rendered"], true);
    }

    #[tokio::test]
    async fn read_terminal_defaults_to_the_snapshot_line_budget() {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: None,
            }),
        );
        let _ = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await;
        assert_eq!(
            shell.await.expect("shell task"),
            Request::ReadTerminal {
                session: 7,
                lines: DEFAULT_TEXT_LINES
            }
        );
    }

    #[tokio::test]
    async fn read_terminal_marks_an_undrawn_screen_as_not_rendered() {
        // Distinct from an unknown handle: the caller should retry, not give up.
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: None,
            }),
        );
        let result = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await
            .expect("an undrawn screen is not an error");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["rendered"], false);
        assert_eq!(value["text"], "");
    }

    #[tokio::test]
    async fn read_terminal_relays_an_unknown_handle_as_invalid_params() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: Some("no live session with handle 7".into()),
            }),
        );
        let error = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await
            .expect_err("a rejected read is a tool error");
        assert!(
            error.message.contains("no live session"),
            "got: {}",
            error.message
        );
    }

    // ---- screenshot: the pixel companion to `snapshot` ----

    /// The image block of a tool result, as `(base64 data, mime type)`.
    fn image_content(result: &CallToolResult) -> (String, String) {
        result
            .content
            .iter()
            .find_map(|block| match block {
                ContentBlock::Image(image) => Some((image.data.clone(), image.mime_type.clone())),
                _ => None,
            })
            .expect("an image content block")
    }

    /// Serve one `screenshot` call with `reply`, returning the tool result and
    /// the request the bridge actually saw.
    async fn call_screenshot(
        args: ScreenshotArgs,
        reply: Reply,
    ) -> (Result<CallToolResult, ErrorData>, Request) {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, reply);
        let result = TermherdMcp::new(handle).screenshot(Parameters(args)).await;
        (result, shell.await.expect("shell task"))
    }

    #[tokio::test]
    async fn screenshot_returns_the_png_as_base64_image_content() {
        let png = vec![0x89u8, 0x50, 0x4e, 0x47, 1, 2, 3];
        let (result, _) = call_screenshot(
            ScreenshotArgs::default(),
            Reply::Shot(ShotResult {
                png: Some(png.clone()),
                width: 1200,
                height: 800,
                error: None,
            }),
        )
        .await;
        let result = result.expect("the tool returns a result");
        let (data, mime) = image_content(&result);
        assert_eq!(mime, "image/png");
        assert_eq!(
            base64::Engine::decode(&base64::engine::general_purpose::STANDARD, &data)
                .expect("valid base64"),
            png,
            "the caller receives exactly the bytes the shell encoded"
        );
    }

    #[tokio::test]
    async fn screenshot_reports_the_dimensions_it_actually_produced() {
        // An agent that asked for 1200 must be able to tell what it got — the
        // window may have been smaller, in which case no upscaling happened.
        let (result, _) = call_screenshot(
            ScreenshotArgs::default(),
            Reply::Shot(ShotResult {
                png: Some(vec![1, 2, 3]),
                width: 800,
                height: 600,
                error: None,
            }),
        )
        .await;
        let value = result
            .expect("a result")
            .structured_content
            .expect("structured json alongside the image");
        assert_eq!(value["width"], 800);
        assert_eq!(value["height"], 600);
    }

    #[tokio::test]
    async fn screenshot_defaults_the_width_bound() {
        let (_, request) = call_screenshot(
            ScreenshotArgs::default(),
            Reply::Shot(ShotResult::failed("no window")),
        )
        .await;
        assert_eq!(
            request,
            Request::Screenshot {
                max_width: DEFAULT_MAX_WIDTH
            },
            "an unparameterised call still bounds the payload"
        );
    }

    #[tokio::test]
    async fn screenshot_clamps_an_out_of_range_width_bound() {
        // Both ends: a caller asking for a thumbnail too small to read, and one
        // asking for more pixels than a tool result should ever carry.
        let (_, tiny) = call_screenshot(
            ScreenshotArgs { max_width: Some(1) },
            Reply::Shot(ShotResult::failed("no window")),
        )
        .await;
        assert_eq!(
            tiny,
            Request::Screenshot {
                max_width: MIN_MAX_WIDTH
            }
        );
        let (_, huge) = call_screenshot(
            ScreenshotArgs {
                max_width: Some(100_000),
            },
            Reply::Shot(ShotResult::failed("no window")),
        )
        .await;
        assert_eq!(
            huge,
            Request::Screenshot {
                max_width: MAX_MAX_WIDTH
            }
        );
    }

    #[tokio::test]
    async fn screenshot_passes_a_width_bound_inside_the_range_through() {
        let (_, request) = call_screenshot(
            ScreenshotArgs {
                max_width: Some(640),
            },
            Reply::Shot(ShotResult::failed("no window")),
        )
        .await;
        assert_eq!(request, Request::Screenshot { max_width: 640 });
    }

    #[tokio::test]
    async fn a_window_less_run_degrades_to_a_readable_tool_error() {
        // Not `Err(ErrorData)`: rmcp renders a protocol error opaquely, and the
        // caller needs to read *why* and that `snapshot` still works.
        let (result, _) = call_screenshot(
            ScreenshotArgs::default(),
            Reply::Shot(ShotResult::failed("no window to screenshot")),
        )
        .await;
        let result = result.expect("a graceful degradation is not a protocol error");
        assert_eq!(result.is_error, Some(true));
        let text = result
            .content
            .iter()
            .filter_map(|block| match block {
                ContentBlock::Text(text) => Some(text.text.clone()),
                _ => None,
            })
            .collect::<String>();
        assert!(
            text.contains("no window to screenshot"),
            "the shell's reason reaches the caller, got {text:?}"
        );
        assert!(
            text.contains("snapshot"),
            "the caller is pointed at the reliable read, got {text:?}"
        );
    }

    #[tokio::test]
    async fn screenshot_rejects_a_wrong_reply_kind_as_an_internal_error() {
        let (result, _) =
            call_screenshot(ScreenshotArgs::default(), Reply::Sessions(Vec::new())).await;
        let error = result.expect_err("a mismatched reply is an internal error");
        assert!(
            error.message.contains("wrong reply kind"),
            "got: {}",
            error.message
        );
    }

    // ---- The keyboard tools (F-mcp-keys) ---------------------------------
    //
    // Both tools are adapters onto one `Request::Press`. These pin the halves
    // the shell cannot: what the tool builds from its arguments, what it rejects
    // before anything applies, and how a step is shaped on the wire.

    use crate::shell::bridge::{Press, PressOutcome, PressStep};
    use termherd_core::keymap::{MOD_CMD, MOD_CTRL, MOD_SHIFT};

    /// An applied press outcome with these steps, focus on handle `2`.
    fn pressed(steps: Vec<PressStep>) -> Reply {
        Reply::Pressed(PressOutcome {
            steps,
            focused: Some("2".into()),
            error: None,
        })
    }

    /// Run `call` against a shell answering with `reply`; return both the tool's
    /// result and the presses it asked for.
    async fn press_request<F, Fut>(call: F, reply: Reply) -> (CallToolResult, Vec<Press>)
    where
        F: FnOnce(TermherdMcp) -> Fut,
        Fut: std::future::Future<Output = Result<CallToolResult, ErrorData>>,
    {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, reply);
        let result = call(TermherdMcp::new(handle))
            .await
            .expect("the tool returns a result");
        match shell.await.expect("shell task") {
            Request::Press(presses) => (result, presses),
            other => panic!("expected a press request, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn press_keys_parses_every_chord_in_order() {
        // The chords reach the shell as parsed `KeyChord`s, in the order asked —
        // a sequence whose order the transport shuffled would be unusable.
        let (_result, presses) = press_request(
            |mcp| async move {
                mcp.press_keys(Parameters(PressKeysArgs {
                    keys: vec!["cmd+shift+s".into(), "ctrl+tab".into(), "escape".into()],
                }))
                .await
            },
            pressed(vec![PressStep::Typed; 3]),
        )
        .await;
        assert_eq!(
            presses,
            vec![
                Press::Chord(KeyChord::new("s", MOD_CMD | MOD_SHIFT)),
                Press::Chord(KeyChord::new("tab", MOD_CTRL)),
                Press::Chord(KeyChord::new("escape", 0)),
            ]
        );
    }

    #[tokio::test]
    async fn run_action_resolves_every_name_including_the_tab_jumps() {
        // Names are the settings.json vocabulary, and the parameterized
        // `activate-tab-N` family is part of it.
        let (_result, presses) = press_request(
            |mcp| async move {
                mcp.run_action(Parameters(RunActionArgs {
                    actions: vec!["split-vertical".into(), "activate-tab-3".into()],
                }))
                .await
            },
            pressed(vec![PressStep::Typed; 2]),
        )
        .await;
        assert_eq!(
            presses,
            vec![
                Press::Command(KeymapAction::SplitVertical),
                // The name's digit is 1-based, the action's index 0-based.
                Press::Command(KeymapAction::ActivateTab(2)),
            ]
        );
    }

    #[tokio::test]
    async fn a_malformed_chord_rejects_the_whole_call_before_anything_applies() {
        // Half a sequence is worse than none: the caller cannot tell how far it
        // got, and the app is left in a state it did not ask for. So the bad
        // chord is caught before the request is even sent.
        let (handle, requests) = channel();
        let error = TermherdMcp::new(handle)
            .press_keys(Parameters(PressKeysArgs {
                keys: vec!["cmd+d".into(), "ctrl+".into()],
            }))
            .await
            .expect_err("an unparsable chord is invalid params");
        assert!(error.message.contains("ctrl+"), "got: {}", error.message);
        assert!(
            error.message.contains("no key"),
            "the parser's reason must reach the caller: {}",
            error.message
        );
        // Nothing was queued: the good first chord never applied either.
        drop(requests);
    }

    #[tokio::test]
    async fn an_unknown_action_name_is_rejected_not_skipped() {
        // Silently dropping an unrecognised name would report a sequence that
        // ran when part of it never did — the silent-catch trap.
        let (handle, requests) = channel();
        let error = TermherdMcp::new(handle)
            .run_action(Parameters(RunActionArgs {
                actions: vec!["split-vertical".into(), "do-the-thing".into()],
            }))
            .await
            .expect_err("an unknown action is invalid params");
        assert!(
            error.message.contains("do-the-thing"),
            "got: {}",
            error.message
        );
        drop(requests);
    }

    #[tokio::test]
    async fn each_step_is_shaped_against_the_press_that_produced_it() {
        // A caller reading "the second one hit a prompt" must not have to count
        // its own arguments to learn which chord that was, so every step echoes
        // its press — and carries only the detail its outcome has.
        let (result, _presses) = press_request(
            |mcp| async move {
                mcp.press_keys(Parameters(PressKeysArgs {
                    keys: vec![
                        "cmd+w".into(),
                        "cmd+d".into(),
                        "x".into(),
                        "f2".into(),
                        "cmd+n".into(),
                        "cmd+shift+t".into(),
                    ],
                }))
                .await
            },
            pressed(vec![
                PressStep::Ran("close-focused".into()),
                PressStep::Overlay("tab-close-confirm".into()),
                PressStep::Typed,
                PressStep::Unbound,
                PressStep::Inert {
                    action: "open-new-session".into(),
                    reason: "no-surface",
                },
                PressStep::Inert {
                    action: "new-claude-session-here".into(),
                    reason: "no-context",
                },
            ]),
        )
        .await;
        let value = result
            .structured_content
            .expect("a press answers with structured content");
        assert_eq!(
            value,
            serde_json::json!({
                "steps": [
                    { "press": "cmd+w", "result": "ran", "action": "close-focused" },
                    { "press": "cmd+d", "result": "overlay", "overlay": "tab-close-confirm" },
                    { "press": "x", "result": "typed" },
                    { "press": "f2", "result": "unbound" },
                    { "press": "cmd+n", "result": "inert",
                      "action": "open-new-session", "reason": "no-surface" },
                    { "press": "cmd+shift+t", "result": "inert",
                      "action": "new-claude-session-here", "reason": "no-context" },
                ],
                "focused_handle": "2",
            }),
        );
    }

    #[tokio::test]
    async fn a_press_that_reached_the_read_only_responder_is_an_internal_error() {
        // The defensive arm in `respond` must surface, not read as an empty
        // sequence — "nothing happened" and "the shell mis-routed this" are
        // different answers and an agent acts differently on each.
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Pressed(PressOutcome {
                steps: Vec::new(),
                focused: None,
                error: Some("a press reached the read-only responder".into()),
            }),
        );
        let error = TermherdMcp::new(handle)
            .run_action(Parameters(RunActionArgs {
                actions: vec!["next-tab".into()],
            }))
            .await
            .expect_err("a mis-routed press is an internal error");
        assert!(
            error.message.contains("read-only responder"),
            "got: {}",
            error.message
        );
        let _ = shell.await;
    }

    #[tokio::test]
    async fn a_step_count_that_does_not_match_the_presses_is_an_internal_error() {
        // The echo is positional. A shell answering a different number of steps
        // would otherwise truncate into a report that reads as correct — worse
        // than an error, because the caller acts on it.
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, pressed(vec![PressStep::Typed]));
        let error = TermherdMcp::new(handle)
            .press_keys(Parameters(PressKeysArgs {
                keys: vec!["cmd+d".into(), "cmd+w".into()],
            }))
            .await
            .expect_err("a step/press mismatch is an internal error");
        assert!(
            error.message.contains("1 steps for 2 presses"),
            "got: {}",
            error.message
        );
        let _ = shell.await;
    }

    #[tokio::test]
    async fn a_press_rejects_a_wrong_reply_kind_as_an_internal_error() {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, Reply::Sessions(Vec::new()));
        let error = TermherdMcp::new(handle)
            .press_keys(Parameters(PressKeysArgs {
                keys: vec!["cmd+d".into()],
            }))
            .await
            .expect_err("a mismatched reply is an internal error");
        assert!(
            error.message.contains("wrong reply kind"),
            "got: {}",
            error.message
        );
        let _ = shell.await;
    }

    #[tokio::test]
    async fn a_press_surfaces_a_bridge_failure_as_an_error() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .press_keys(Parameters(PressKeysArgs {
                keys: vec!["cmd+d".into()],
            }))
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(error.message.contains("closed"), "got: {}", error.message);
    }
}
